proj/admin/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileField
from wtforms.fields import SubmitField, PasswordField, StringField, DecimalField
from wtforms.validators import DataRequired


class AdminLoginForm(FlaskForm):
    username = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号！")
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入账号！",
        }
    )
    password = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-lg btn-primary btn-block",
        }
    )


class CpuForm(FlaskForm):
    name = StringField(
        label=u"商品名",
        validators=[
            DataRequired()
        ],
        render_kw={
            "class": "form-control",
        }
    )
    slogan = StringField(
        label=u"商品描述",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    sale_price = DecimalField(
        label=u'售卖价格',
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    commodity_figure_path = FileField(
        label=u'商品图片',
        validators=[
            FileRequired(),
        ],
        render_kw={
            "class": "form-control",
            'accept': 'image/jpeg,image/png,image/jpg'
        }
    )
    interface = StringField(
        label=u"接口类型",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    match_mainboard = StringField(
        label=u"搭配主板",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    series = StringField(
        label=u"系列",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    model = StringField(
        label=u"型号",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    core_count = StringField(
        label=u"核心数量",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    GHz = StringField(
        label=u"主频",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    manufacturing_technique = StringField(
        label=u"制造工艺",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    power = StringField(
        label=u"功率",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    # multi_img = MultipleFileField(
    #     label='多图片',
    #     render_kw={
    #         "class": "form-control",
    #     }
    # )
    submit = SubmitField(
        '提交',
        render_kw={
            "class": "btn btn-success",
        }
    )

proj/__init__.py
from flask import Flask
from flask_admin.base import Admin
from flask_admin.contrib.sqla import ModelView
from flask_redis import FlaskRedis
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
rd = FlaskRedis()

# class MyView(BaseView):
#     @expose('/')
#     def index(self):
#         return self.render('index.html')



f_admin = Admin(name='后台管理',template_mode='bootstrap3',endpoint='admin_back')
from .models import Users, OrderDetail, Order,UserDetail,Store
from .admin_model import OrderView,AvatarView,OrderDetailView,StoreView,CpuAddView




f_admin.add_view(CpuAddView(name='cpu_add'))
f_admin.add_view(OrderView(db.session))
f_admin.add_view(OrderDetailView(db.session))
f_admin.add_view(AvatarView(UserDetail,db.session))
f_admin.add_view(StoreView(Store,db.session))


def create_app():
    app = Flask(__name__)
    app.config.from_object('proj.settings.LocalTestingConfig')
    from .usr import usr as usr_blueprint
    from .web import web as web_blueprint
    from .admin import admin as admin_blueprint
    app.register_blueprint(usr_blueprint, url_prefix='/user')
    app.register_blueprint(admin_blueprint, url_prefix='/admin')
    app.register_blueprint(web_blueprint)

    db.init_app(app)
    rd.init_app(app)
    f_admin.init_app(app)
    return app

proj/admin/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from flask import Blueprint

admin = Blueprint(
    'admin',
    __name__,
    template_folder='templates',
    static_folder='static',
)
from . import views

proj/admin/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from flask import session, redirect, render_template, flash, url_for, request
from werkzeug.utils import secure_filename

from . import admin
from .forms import AdminLoginForm, CpuForm
from .. import db
from ..models import Store, CpuProduct, CpuDetail, ProductID


@admin.before_request
def auth():
    admin = session.get('admin')
    if not admin:
        if request.path != url_for('admin.login'):
            return redirect(url_for('admin.login'))
@admin.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('admin.login'))


@admin.route('/')
def index():
    return render_template('admin/admin_main.html')


@admin.route('/login/', methods=["GET", "POST"])
def login():
    form = AdminLoginForm()
    if form.validate_on_submit():
        data = form.data
        store = Store.query.filter_by(admin_username=data["username"], admin_password=data['password']).first()
        if not store:
            flash('帐号或密码错误', 'err')
            return redirect(url_for('admin.login'))
        session["admin"] = store.name
        return redirect(url_for('admin.index'))
    return render_template('admin/login.html', form=form)


@admin.route('/add_cpu', methods=['get', 'post'])
def add_cpu():
    form = CpuForm()
    if form.validate_on_submit():
        data = form.data
        store = Store.query.filter_by(name=session['admin']).first()
        image_name = secure_filename(form.commodity_figure_path.data.filename)
        from ..web.views import app
        form.commodity_figure_path.data.save(app.config['STATIC_DIR'] + '/files/product_image/' + image_name)
        pid = ProductID(category='cpu')

        cpu = CpuProduct(name=data['name'], PID=pid.id, slogan=data['slogan'], sale_price=data['sale_price'],
                         commodity_figure_path='/files/product_image/' + image_name, store_id=store.id)
        pid.object = cpu
        detail = CpuDetail(cpu_id=cpu.id, brand=store.brand, interface=data['interface'],
                           match_mainboard=data['match_mainboard'],
                           series=data['series'], model=data['model'], core_count=data['core_count'], GHz=data['GHz'],
                           manufacturing_technique=data['manufacturing_technique'], power=data['power'])
        db.session.add_all([pid, cpu, detail])
        db.session.commit()
        ProductID.query.filter_by(id=pid.id).update({'object_id': cpu.id})
        CpuProduct.query.filter_by(id=cpu.id).update({'PID': pid.id})
        CpuDetail.query.filter_by(id=detail.id).update({'cpu_id': cpu.id})
        db.session.commit()

    return render_template('admin/add_cpu.html', form=form)

proj/usr/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from flask import Blueprint

usr = Blueprint(
    'usr',
    __name__,
    template_folder='templates',
    static_folder='static'
)
from . import views

proj/usr/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

import datetime
import json
import os

from flask import render_template, flash, redirect, url_for, session, request, jsonify
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

from . import usr
from .forms import PwdForm, AvatarForm
from .. import db, rd
from ..models import Users, UserDetail, ProductID, Order, OrderDetail, AlipayOrder
from ..web.views import ali


@usr.before_request
def auth():
    user = session.get('user')
    # print(url_for('web.login'))
    if not user:
        if request.method == 'POST':
            return jsonify({'status': 'success', 'url': url_for('web.login') + '?return_url=%s' % request.referrer})
        flash('请先登录', category='err')
        return redirect(url_for('web.login') + '?return_url=%s' % request.path)


@usr.route('/')
def index():
    return render_template('usr/user_base.html')


@usr.route('/info/')
def userinfo():
    return render_template('usr/userinfo.html')


@usr.route('/info/modify_password/', methods=["GET", "POST"])
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = Users.query.filter_by(username=session["user"])
        if not user.first().check_pwd(data["old_pwd"]):
            flash("旧密码错误！", "err")
            return redirect(url_for('usr.pwd'))
        new_pwd = generate_password_hash(data["new_pwd"])
        user.update({'password': new_pwd})
        db.session.commit()
        return redirect(url_for('web.logout'))
    return render_template("usr/modify_password.html", form=form)


@usr.route('/info/avatar/', methods=["GET", "POST"])
def avatar():
    from ..web.views import app
    form = AvatarForm()
    if form.validate_on_submit():
        avatar_name = secure_filename(form.avatar.data.filename)
        detail = UserDetail.query.filter_by(user_id=session['user_id'])
        if detail.first().avatar:
            os.remove(app.config['STATIC_DIR'] + os.path.sep + detail.first().avatar)
        detail.update({'avatar': 'files/avatar/' + avatar_name})
        db.session.commit()
        form.avatar.data.save(app.config['STATIC_DIR'] + '/files/avatar/' + avatar_name)
        session['avatar'] = 'files/avatar/' + avatar_name
        flash('上传头像成功！', category='success')
        return redirect(url_for('usr.avatar'))
    return render_template("usr/edit_avatar.html", form=form)


@usr.route('/add_to_cart/', methods=['post'])
def add_to_cart():
    count = request.form.get('count')
    pid = request.form.get('pid')
    user_id = session.get('user_id')
    user_cart_list = rd.hget('user_cart', user_id)
    if not user_cart_list:
        rd.hset('user_cart', user_id, json.dumps([(pid, count), ]))
    else:
        user_cart_list = json.loads(user_cart_list)
        for i in user_cart_list:
            if i[0] == pid:
                i[1] = str(int(i[1]) + int(count))
                break
        else:
            user_cart_list.append((pid, count))
        rd.hset('user_cart', user_id, json.dumps(user_cart_list))
    session["cart_count"] = get_cart_count(user_id)
    return jsonify({'status': 'success', 'url': url_for('usr.cart')})


@usr.route('/cart/', methods=['get', 'post'])
def cart():
    user_cart_list = rd.hget('user_cart', session['user_id'])
    list = None
    if not user_cart_list:
        pass
    else:
        user_cart_list = json.loads(user_cart_list)
        list = [(ProductID.query.filter_by(id=int(li[0])).first(), int(li[1])) for li in user_cart_list]
    return render_template('usr/cart.html', list=list)


@usr.route('/cart_change/', methods=['post'])
def cart_change():
    func = request.form.get('func')
    pid = request.form.get('pid')
    user_id = session.get('user_id')
    user_cart_list = json.loads(rd.hget('user_cart', user_id))
    count = ''
    for i in user_cart_list:
        if i[0] == pid:
            if func == '+':
                count = i[1] = str(int(i[1]) + 1)
                print(count)
            else:
                count = i[1] = str(int(i[1]) - 1)
            break
    rd.hset('user_cart', user_id, json.dumps(user_cart_list))
    session["cart_count"] = get_cart_count(user_id)
    return jsonify({'status': 'success', 'count': count})


@usr.route('/delete_item')
def cart_delete_item():
    item = request.args.get('item')
    user_id = int(session.get('user_id'))
    user_cart_list = json.loads(rd.hget('user_cart', user_id))
    for order in user_cart_list:
        if order[0] == item:
            print(item, order[0])
            user_cart_list.remove(order)
            break
    rd.hset('user_cart', user_id, json.dumps(user_cart_list))
    session["cart_count"] = get_cart_count(user_id)
    return redirect(url_for('usr.cart'))


@usr.route('/create_order/', methods=['post'])
def create_order():
    user_id = session.get('user_id')
    order_list = json.loads(request.form.get('list'))
    # user_cart_list = json.loads(rd.hget('user_cart', user_id))
    sum = 0
    orderlist = []
    user_cart_list = json.loads(rd.hget('user_cart', user_id))
    alipay_order = AlipayOrder()
    db.session.add(alipay_order)
    db.session.commit()
    for i in order_list:
        obj_id = int(i[0])
        for j in user_cart_list:
            if int(j[0]) == obj_id:
                user_cart_list.remove(j)
                continue
        count = int(i[1])
        obj = ProductID.query.filter_by(id=obj_id).first()
        price = float(obj.object.sale_price) * count
        sum += price
        order = Order(status='0', user_id=user_id, count=count, alipay_id=alipay_order.id)
        db.session.add(order)
        db.session.commit()
        detail = OrderDetail(order_id=order.id, object_type=obj.object_type, object_id=obj.object_id)
        db.session.add(detail)
        db.session.commit()
        orderlist.append(order.id)
    AlipayOrder.query.filter_by(id=alipay_order.id).update({'sum': sum})
    db.session.commit()
    send_order_expired_task(orderlist)  # 发送订单自动删除请求
    rd.hset('user_cart', user_id, json.dumps(user_cart_list))  # 从购物车中移除商品
    return jsonify({'status': 'success', 'url': url_for('usr.user_order_unpay')})


def send_order_expired_task(orderlist):
    '''
    30分钟如果未付款，自动关闭订单
    '''
    ctime = datetime.datetime.now()
    utc_ctime = datetime.datetime.utcfromtimestamp(ctime.timestamp())
    time_delay = datetime.timedelta(minutes=1)
    task_time = utc_ctime + time_delay  # 设定延迟执行时间
    from ..celery_task.order_expired import order_auto_expired
    order_auto_expired.apply_async(args=[orderlist], eta=task_time)


@usr.route('/user_order')
def user_order():
    orders = Order.query.filter_by(user_id=session['user_id']).order_by(Order.ordered_time.desc())
    return render_template('usr/userorder_all.html', orders=orders)


@usr.route('/user_order_unpay')
def user_order_unpay():
    '''
    优惠券及秒杀打折业务逻辑暂未写，未返回前端当前用户有哪些可享用的折扣
    '''
    lists = []

    orders = Order.query.filter_by(user_id=session['user_id'], status='0').order_by(Order.ordered_time.desc()).all()
    if not orders:
        alipay_id = ''
    else:
        alipay_id = orders[0].alipay_id
    for order in orders:
        lists.append((ProductID.query.filter_by(id=order.detail.object.PID).first(), order.count, order.id))
    return render_template('usr/unpay.html', lists=lists, alipay_id=alipay_id)


@usr.route('/before_send', methods=['get'])
def before_send():
    '''

    order_dict={'alipay_id1':{'orders':[order1,order2,],'sum':sum},'alipay_id2':{...}}
    '''
    user_id = session.get('user_id')
    orders = Order.query.filter_by(user_id=user_id, status='2').order_by(Order.ordered_time.desc()).all()
    order_dict = {}
    for order in orders:
        if order.alipay_id not in order_dict:
            order_dict[order.alipay_id] = {}
            order_dict[order.alipay_id]['orders'] = [order, ]
            order_dict[order.alipay_id]['sum'] = order.alipay_order.sum
        else:
            order_dict[order.alipay_id]['orders'].append(order)
    return render_template('usr/has_payed.html', order_dict=order_dict)


@usr.route('/go_pay', methods=['post'])
def redirect_alipay():
    alipay_id = request.form.get('alipay_id')
    money = float(AlipayOrder.query.filter_by(id=int(alipay_id)).first().sum)
    # 生成一个对象
    alipay = ali()
    # 生成支付的url
    # 对象调用direct_pay
    # 该方法生成一个加密串
    query_params = alipay.direct_pay(
        subject="hy商城购物订单",  # 商品简单描述
        out_trade_no=str(alipay_id),  # 商户订单号
        total_amount=money,  # 交易金额(单位: 元 保留俩位小数)
    )
    pay_url = "https://openapi.alipaydev.com/gateway.do?{}".format(query_params)
    return jsonify({'status': 'success', 'url': pay_url})


def get_cart_count(user_id):
    user_cart_list = rd.hget('user_cart', user_id)
    if not user_cart_list:
        return 0
    user_cart_list=json.loads(user_cart_list)
    sum = 0
    for items in user_cart_list:
        sum += int(items[1])
    return sum

proj/web/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from flask import Blueprint

web = Blueprint(
    'web',
    __name__,
    template_folder='templates',
    static_folder='static'
)
from . import views

proj/templates/usr/cart.html
{% extends 'usr/user_base.html' %}
{% block css %}
    <style>
        .quantity-remove, .quantity-add {
            cursor: pointer;
        }

        .quantity-add.glyphicon, .quantity-remove.glyphicon {
            display: block;
            cursor: pointer;
        }

        input {
            width: 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">全部商品</div>
        <div class="panel-body">
        </div>
    {% if list %}
        <table class="table">
            <thead>
            <tr>
                <td class="col-md-1">全选</td>
                <td class="col-md-5">商品</td>
                <td>单价</td>
                <td>数量</td>
                <td>小计</td>
                <td>操作</td>
            </tr>

                {% for item in list %}
                    <tr class="rrow">
                        <td>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" class="check">
                                </label>
                            </div>
                        </td>
                        <td>
                            <div class="media">
                                <div class="media-left">
                                    <a href="#">
                                        <img class="media-object" src="/static{{ item.0.object.commodity_figure_path }}"
                                             alt="..." style="width: 100px">
                                    </a>
                                </div>
                                <div class="media-body">
                                    <h6 class="media-heading">{{ item.0.object.name }}</h6>
                                </div>
                            </div>
                        </td>
                        <td class="price">{{ item.0.object.sale_price }}</td>
                        <td class="count" bb="{{ item.0.id }}">
                            <div>
                                <a class="btn btn-default">-</a>
                                <input class="input" value="{{ item.1 }}" type="text"/>
                                <a class="btn btn-default plus">+</a>
                            </div>

                        </td>
                        <td class="money">

                        </td>
                        <td><a href="{{ url_for('usr.cart_delete_item') }}?item={{ item.0.id }}">删除</a></td>
                    </tr>
                {% endfor %}


                </thead>
                </table>
                <div class="col-md-offset-7 col-md-3"><h4>总价：<b class="sum" style='color: red'>￥0.00</b></h4></div>
                <div class=col-md-2">
                    <p style="width: 100%;"><a class="btn btn-primary btn-lg" role="button"
                                               style="color:whitesmoke;">提交订单</a></p>
                </div>
            {% else %}
            <h2 class="pull-right">购物车内暂无商品</h2>
            {% endif %}

    </div>
{% endblock %}
{% block script %}
    <script>
        $('.btn-default').on('click', function () {
            var func = '';
            var _this = this
            var pid = $(this).parent().parent().attr('bb');
            if ($(this).hasClass('plus')) {
                func = '+'
            } else {
                func = '-'
                if ($(this).parent().children('input').val() < 2) {
                    return
                }
            }
            $.ajax({
                url: '{{ url_for('usr.cart_change') }}',
                method: 'post',
                data: {'func': func, 'pid': pid},
                success: function (data) {
                    if (data.status == 'success') {
                        $(_this).parent().children('input').attr('value', data.count)
                        reset()
                        sum_all()

                    }
                }
            })
        })
        $('.btn-lg').on('click', function () {

            $.ajax({
                url: '{{ url_for('usr.create_order') }}',
                method: 'post',
                data: {'list': JSON.stringify(gather_all())},
                success: function (data) {
                    if (data.status == 'success') {
                        window.location.href = data.url
                    }
                }
            })
        })
        $(document).ready(function () {
            reset()
        })

        function reset() {
            $('.rrow').each(function () {
                var a = $(this).children('.price').text();
                var b = $(this).children('.count').children().children('input').val()
                $(this).children('.money').text('￥' + (parseInt(a) * parseInt(b)).toFixed(2))
            })
        }

        $('.check').on('click', function () {
            if ($(this).hasClass('checked')) {
                $(this).removeClass('checked')
            } else {
                $(this).addClass('checked')
            }
            sum_all()


        })

        function sum_all() {
            var sum = 0
            $('.checked').each(function () {
                var a = $(this).parents('td').nextAll('.money').text().slice(1)
                sum = sum + parseInt(a)
            })
            $('.sum').text('￥' + sum.toFixed(2))
        }

        function gather_all() {
            var list = []
            $('.checked').each(function () {
                list.push([$(this).parents('td').nextAll('.count').attr('bb'),
                    $(this).parents('td').nextAll('.count').children('div').children('.input').val()])
            })
            return list


        }
    </script>

{% endblock %}

proj/templates/usr/edit_avatar.html
{% extends 'usr/userinfo.html' %}
{% block edit %}
    <div class="panel panel-default">
        <div class="panel-body">
            {% for msg in get_flashed_messages(category_filter=["err"]) %}
                <p style="color:red;">{{ msg }}</p>
            {% endfor %}
            {% for msg in get_flashed_messages(category_filter=["success"]) %}
                <p style="color:green;">{{ msg }}</p>
            {% endfor %}
            <img style="width: 150px;height: 150px" id="img"
                 src="{% if session.avatar %}/static/{{ session.avatar }}{% else %}/static/files/avatar/no-img.jpg{% endif %}"
                 alt="..."
                 class="img-circle-rounded">
            <form role="form" method="post" enctype="multipart/form-data">
                <fieldset>
                    <div class="form-group">
                        <label for="input_oldpwd"><span
                                class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.avatar.label }}</label>
                        {{ form.avatar }}
                    </div>
                    {{ form.csrf_token }}
                    {{ form.submit }}
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $('#avatar').on('change', function () {
            var file = $('#avatar')[0].files[0];
            var file_reader = new FileReader();
            file_reader.readAsDataURL(file);
            file_reader.onload = function () {
                $('img').attr('src', file_reader.result, 'style', 'width: 100px;height: 100px')
            }
        });
    </script>
{% endblock %}

proj/templates/usr/has_payed.html
{% extends 'usr/userorder.html' %}
{% block order %}
    {% for order in order_dict.items() %}
        <div class="panel panel-default">
            <div class="panel-heading">支付编号:{{ order.0 }}<span class="pull-right" style="color: darkred;">付款额:{{ order.1.sum }}</span></div>
            <div class="panel-body">
                {% for foo in order.1.orders %}
                    <p>{{ foo.detail.object.name }}*{{ foo.count }}</p>
                {% endfor %}

                <p></p>
            </div>
        </div>
    {% endfor %}

{% endblock %}


{% block script %}
    <script>
        $(document).ready(function () {
            $('.unsend').addClass('active')
        })
    </script>
{% endblock %}

proj/templates/usr/modify_password.html
{% extends 'usr/userinfo.html' %}
{% block edit %}
    <div class="panel panel-default">
        <div class="panel-body">
            {% for msg in get_flashed_messages(category_filter=["err"]) %}
                <p style="color:red;">{{ msg }}</p>
            {% endfor %}
            {% for msg in get_flashed_messages(category_filter=["ok"]) %}
                <p style="color:green;">{{ msg }}</p>
            {% endfor %}
            <form role="form" method="post">
                <fieldset>
                    <div class="form-group">
                        <label for="input_oldpwd"><span
                                class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.old_pwd.label }}</label>
                        {{ form.old_pwd }}
                    </div>
                    {% for err in form.old_pwd.errors %}
                        <div class="col-md-12">
                            <font style="color:red">{{ err }}</font>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <label for="input_newpwd"><span
                                class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.new_pwd.label }}</label>
                        {{ form.new_pwd }}
                    </div>
                    {% for err in form.new_pwd.errors %}
                        <div class="col-md-12">
                            <font style="color:red">{{ err }}</font>
                        </div>
                    {% endfor %}
                    {{ form.csrf_token }}
                    {{ form.submit }}
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}

proj/templates/usr/unpay.html
{% extends 'usr/userorder.html' %}
{% block order %}
    <table class="table">
        <thead>
        <tr>
            <td>订单号</td>
            <td class="col-md-5">商品</td>
            <td>单价</td>
            <td>数量</td>
            <td>小计</td>
        </tr>
        {% for item in lists %}
            <tr class="rrow">
                <td>{{ item.2 }}</td>
                <td>
                    <div class="media">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object" src="/static{{ item.0.object.commodity_figure_path }}"
                                     alt="..." style="width: 100px">
                            </a>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading">{{ item.0.object.name }}</h6>
                        </div>
                    </div>
                </td>
                <td class="price">{{ item.0.object.sale_price }}</td>
                <td class="count">
                    {{ item.1 }}
                </td>
                <td class="money">

                </td>
            </tr>
        {% endfor %}

        </thead>
    </table>
    <div class="col-md-offset-7 col-md-3"><h4>总价：<b class="sum" style='color: red'>￥0.00</b></h4></div>
    <div class=col-md-2">
        <p style="width: 100%;"><a class="btn btn-primary btn-lg" aa="{{ alipay_id }}" role="button"
                                   style="color:whitesmoke;">去支付</a></p>

    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('.unpay').addClass('active')
            reset()
            sum_all()
        })

        function sum_all() {
            var sum = 0
            $('.rrow').each(function () {
                var a = $(this).children('.money').text().slice(1)
                sum = sum + parseInt(a)
            })
            $('.sum').text('￥' + sum.toFixed(2))
        }

        function reset() {
            $('.rrow').each(function () {
                var a = $(this).children('.price').text();
                var b = $(this).children('.count').text()
                $(this).children('.money').text('￥' + (parseInt(a) * parseInt(b)).toFixed(2))
            })
        }
        $('.btn-lg').on('click',function () {
            $.ajax({
                url:'{{ url_for('usr.redirect_alipay') }}',
                method:'post',
                data:{'alipay_id':$(this).attr('aa')},
                success:function (data) {
                    console.log(data)
                    if (data.status=='success'){
                        window.location.href=data.url
                    }
                }
            })
        })
    </script>

{% endblock %}

proj/templates/usr/user_base.html
{% extends 'web/basehome.html' %}
{% block search %}
    <div class="container">
        <div class="row col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation" class="active"><a href="#">订单中心</a></li>
                <li role="presentation"><a href="{{ url_for('usr.user_order') }}">我的订单</a></li>
                <li role="presentation"><a href="{{ url_for('usr.cart') }}">购物车</a></li>
            </ul>
            <br>
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation" class="active"><a href="#">用户中心</a></li>
                <li role="presentation"><a href="/user/info/">个人信息</a></li>
                <li role="presentation"><a href="#">PLUS会员</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            {% block content %}
                {% endblock %}
        </div>
    </div>

{% endblock %}

proj/templates/usr/userorder.html
{% extends 'usr/user_base.html' %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <ul class="nav nav-pills">
                <li role="presentation" class="all"><a href="{{ url_for('usr.user_order') }}">全部订单</a></li>
                <li role="presentation" class="unpay"><a href="{{ url_for('usr.user_order_unpay') }}">待付款</a></li>
                <li role="presentation" class="unsend"><a href="{{ url_for('usr.before_send') }}">待发货</a></li>
            </ul>
        </div>
        {% block order %}
            {% endblock %}

    </div>
{% endblock %}