proj/admin/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileField
from wtforms.fields import SubmitField, PasswordField, StringField, DecimalField
from wtforms.validators import DataRequired


class AdminLoginForm(FlaskForm):
    username = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号！")
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入账号！",
        }
    )
    password = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-lg btn-primary btn-block",
        }
    )


class CpuForm(FlaskForm):
    name = StringField(
        label=u"商品名",
        validators=[
            DataRequired()
        ],
        render_kw={
            "class": "form-control",
        }
    )
    slogan = StringField(
        label=u"商品描述",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    sale_price = DecimalField(
        label=u'售卖价格',
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    commodity_figure_path = FileField(
        label=u'商品图片',
        validators=[
            FileRequired(),
        ],
        render_kw={
            "class": "form-control",
            'accept': 'image/jpeg,image/png,image/jpg'
        }
    )
    interface = StringField(
        label=u"接口类型",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    match_mainboard = StringField(
        label=u"搭配主板",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    series = StringField(
        label=u"系列",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    model = StringField(
        label=u"型号",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    core_count = StringField(
        label=u"核心数量",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    GHz = StringField(
        label=u"主频",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    manufacturing_technique = StringField(
        label=u"制造工艺",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    power = StringField(
        label=u"功率",
        validators=[
            DataRequired(),
        ],
        render_kw={
            "class": "form-control",
        }
    )
    # multi_img = MultipleFileField(
    #     label='多图片',
    #     render_kw={
    #         "class": "form-control",
    #     }
    # )
    submit = SubmitField(
        '提交',
        render_kw={
            "class": "btn btn-success",
        }
    )

proj/__init__.py
from flask import Flask
from flask_admin.base import Admin
from flask_admin.contrib.sqla import ModelView
from flask_redis import FlaskRedis
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
rd = FlaskRedis()

# class MyView(BaseView):
#     @expose('/')
#     def index(self):
#         return self.render('index.html')



f_admin = Admin(name='后台管理',template_mode='bootstrap3',endpoint='admin_back')
from .models import Users, OrderDetail, Order,UserDetail,Store
from .admin_model import OrderView,AvatarView,OrderDetailView,StoreView,CpuAddView




f_admin.add_view(CpuAddView(name='cpu_add'))
f_admin.add_view(OrderView(db.session))
f_admin.add_view(OrderDetailView(db.session))
f_admin.add_view(AvatarView(UserDetail,db.session))
f_admin.add_view(StoreView(Store,db.session))


def create_app():
    app = Flask(__name__)
    app.config.from_object('proj.settings.LocalTestingConfig')
    from .usr import usr as usr_blueprint
    from .web import web as web_blueprint
    from .admin import admin as admin_blueprint
    app.register_blueprint(usr_blueprint, url_prefix='/user')
    app.register_blueprint(admin_blueprint, url_prefix='/admin')
    app.register_blueprint(web_blueprint)

    db.init_app(app)
    rd.init_app(app)
    f_admin.init_app(app)
    return app

proj/admin/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from flask import Blueprint

admin = Blueprint(
    'admin',
    __name__,
    template_folder='templates',
    static_folder='static',
)
from . import views

proj/admin/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from flask import session, redirect, render_template, flash, url_for, request
from werkzeug.utils import secure_filename

from . import admin
from .forms import AdminLoginForm, CpuForm
from .. import db
from ..models import Store, CpuProduct, CpuDetail, ProductID


@admin.before_request
def auth():
    admin = session.get('admin')
    if not admin:
        if request.path != url_for('admin.login'):
            return redirect(url_for('admin.login'))
@admin.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('admin.login'))


@admin.route('/')
def index():
    return render_template('admin/admin_main.html')


@admin.route('/login/', methods=["GET", "POST"])
def login():
    form = AdminLoginForm()
    if form.validate_on_submit():
        data = form.data
        store = Store.query.filter_by(admin_username=data["username"], admin_password=data['password']).first()
        if not store:
            flash('帐号或密码错误', 'err')
            return redirect(url_for('admin.login'))
        session["admin"] = store.name
        return redirect(url_for('admin.index'))
    return render_template('admin/login.html', form=form)


@admin.route('/add_cpu', methods=['get', 'post'])
def add_cpu():
    form = CpuForm()
    if form.validate_on_submit():
        data = form.data
        store = Store.query.filter_by(name=session['admin']).first()
        image_name = secure_filename(form.commodity_figure_path.data.filename)
        from ..web.views import app
        form.commodity_figure_path.data.save(app.config['STATIC_DIR'] + '/files/product_image/' + image_name)
        pid = ProductID(category='cpu')

        cpu = CpuProduct(name=data['name'], PID=pid.id, slogan=data['slogan'], sale_price=data['sale_price'],
                         commodity_figure_path='/files/product_image/' + image_name, store_id=store.id)
        pid.object = cpu
        detail = CpuDetail(cpu_id=cpu.id, brand=store.brand, interface=data['interface'],
                           match_mainboard=data['match_mainboard'],
                           series=data['series'], model=data['model'], core_count=data['core_count'], GHz=data['GHz'],
                           manufacturing_technique=data['manufacturing_technique'], power=data['power'])
        db.session.add_all([pid, cpu, detail])
        db.session.commit()
        ProductID.query.filter_by(id=pid.id).update({'object_id': cpu.id})
        CpuProduct.query.filter_by(id=cpu.id).update({'PID': pid.id})
        CpuDetail.query.filter_by(id=detail.id).update({'cpu_id': cpu.id})
        db.session.commit()

    return render_template('admin/add_cpu.html', form=form)

proj/usr/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from flask import Blueprint

usr = Blueprint(
    'usr',
    __name__,
    template_folder='templates',
    static_folder='static'
)
from . import views

proj/usr/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

import datetime
import json
import os

from flask import render_template, flash, redirect, url_for, session, request, jsonify
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

from . import usr
from .forms import PwdForm, AvatarForm
from .. import db, rd
from ..models import Users, UserDetail, ProductID, Order, OrderDetail, AlipayOrder
from ..web.views import ali


@usr.before_request
def auth():
    user = session.get('user')
    # print(url_for('web.login'))
    if not user:
        if request.method == 'POST':
            return jsonify({'status': 'success', 'url': url_for('web.login') + '?return_url=%s' % request.referrer})
        flash('请先登录', category='err')
        return redirect(url_for('web.login') + '?return_url=%s' % request.path)


@usr.route('/')
def index():
    return render_template('usr/user_base.html')


@usr.route('/info/')
def userinfo():
    return render_template('usr/userinfo.html')


@usr.route('/info/modify_password/', methods=["GET", "POST"])
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = Users.query.filter_by(username=session["user"])
        if not user.first().check_pwd(data["old_pwd"]):
            flash("旧密码错误！", "err")
            return redirect(url_for('usr.pwd'))
        new_pwd = generate_password_hash(data["new_pwd"])
        user.update({'password': new_pwd})
        db.session.commit()
        return redirect(url_for('web.logout'))
    return render_template("usr/modify_password.html", form=form)


@usr.route('/info/avatar/', methods=["GET", "POST"])
def avatar():
    from ..web.views import app
    form = AvatarForm()
    if form.validate_on_submit():
        avatar_name = secure_filename(form.avatar.data.filename)
        detail = UserDetail.query.filter_by(user_id=session['user_id'])
        if detail.first().avatar:
            os.remove(app.config['STATIC_DIR'] + os.path.sep + detail.first().avatar)
        detail.update({'avatar': 'files/avatar/' + avatar_name})
        db.session.commit()
        form.avatar.data.save(app.config['STATIC_DIR'] + '/files/avatar/' + avatar_name)
        session['avatar'] = 'files/avatar/' + avatar_name
        flash('上传头像成功！', category='success')
        return redirect(url_for('usr.avatar'))
    return render_template("usr/edit_avatar.html", form=form)


@usr.route('/add_to_cart/', methods=['post'])
def add_to_cart():
    count = request.form.get('count')
    pid = request.form.get('pid')
    user_id = session.get('user_id')
    user_cart_list = rd.hget('user_cart', user_id)
    if not user_cart_list:
        rd.hset('user_cart', user_id, json.dumps([(pid, count), ]))
    else:
        user_cart_list = json.loads(user_cart_list)
        for i in user_cart_list:
            if i[0] == pid:
                i[1] = str(int(i[1]) + int(count))
                break
        else:
            user_cart_list.append((pid, count))
        rd.hset('user_cart', user_id, json.dumps(user_cart_list))
    session["cart_count"] = get_cart_count(user_id)
    return jsonify({'status': 'success', 'url': url_for('usr.cart')})


@usr.route('/cart/', methods=['get', 'post'])
def cart():
    user_cart_list = rd.hget('user_cart', session['user_id'])
    list = None
    if not user_cart_list:
        pass
    else:
        user_cart_list = json.loads(user_cart_list)
        list = [(ProductID.query.filter_by(id=int(li[0])).first(), int(li[1])) for li in user_cart_list]
    return render_template('usr/cart.html', list=list)


@usr.route('/cart_change/', methods=['post'])
def cart_change():
    func = request.form.get('func')
    pid = request.form.get('pid')
    user_id = session.get('user_id')
    user_cart_list = json.loads(rd.hget('user_cart', user_id))
    count = ''
    for i in user_cart_list:
        if i[0] == pid:
            if func == '+':
                count = i[1] = str(int(i[1]) + 1)
                print(count)
            else:
                count = i[1] = str(int(i[1]) - 1)
            break
    rd.hset('user_cart', user_id, json.dumps(user_cart_list))
    session["cart_count"] = get_cart_count(user_id)
    return jsonify({'status': 'success', 'count': count})


@usr.route('/delete_item')
def cart_delete_item():
    item = request.args.get('item')
    user_id = int(session.get('user_id'))
    user_cart_list = json.loads(rd.hget('user_cart', user_id))
    for order in user_cart_list:
        if order[0] == item:
            print(item, order[0])
            user_cart_list.remove(order)
            break
    rd.hset('user_cart', user_id, json.dumps(user_cart_list))
    session["cart_count"] = get_cart_count(user_id)
    return redirect(url_for('usr.cart'))


@usr.route('/create_order/', methods=['post'])
def create_order():
    user_id = session.get('user_id')
    order_list = json.loads(request.form.get('list'))
    # user_cart_list = json.loads(rd.hget('user_cart', user_id))
    sum = 0
    orderlist = []
    user_cart_list = json.loads(rd.hget('user_cart', user_id))
    alipay_order = AlipayOrder()
    db.session.add(alipay_order)
    db.session.commit()
    for i in order_list:
        obj_id = int(i[0])
        for j in user_cart_list:
            if int(j[0]) == obj_id:
                user_cart_list.remove(j)
                continue
        count = int(i[1])
        obj = ProductID.query.filter_by(id=obj_id).first()
        price = float(obj.object.sale_price) * count
        sum += price
        order = Order(status='0', user_id=user_id, count=count, alipay_id=alipay_order.id)
        db.session.add(order)
        db.session.commit()
        detail = OrderDetail(order_id=order.id, object_type=obj.object_type, object_id=obj.object_id)
        db.session.add(detail)
        db.session.commit()
        orderlist.append(order.id)
    AlipayOrder.query.filter_by(id=alipay_order.id).update({'sum': sum})
    db.session.commit()
    send_order_expired_task(orderlist)  # 发送订单自动删除请求
    rd.hset('user_cart', user_id, json.dumps(user_cart_list))  # 从购物车中移除商品
    return jsonify({'status': 'success', 'url': url_for('usr.user_order_unpay')})


def send_order_expired_task(orderlist):
    '''
    30分钟如果未付款，自动关闭订单
    '''
    ctime = datetime.datetime.now()
    utc_ctime = datetime.datetime.utcfromtimestamp(ctime.timestamp())
    time_delay = datetime.timedelta(minutes=1)
    task_time = utc_ctime + time_delay  # 设定延迟执行时间
    from ..celery_task.order_expired import order_auto_expired
    order_auto_expired.apply_async(args=[orderlist], eta=task_time)


@usr.route('/user_order')
def user_order():
    orders = Order.query.filter_by(user_id=session['user_id']).order_by(Order.ordered_time.desc())
    return render_template('usr/userorder_all.html', orders=orders)


@usr.route('/user_order_unpay')
def user_order_unpay():
    '''
    优惠券及秒杀打折业务逻辑暂未写，未返回前端当前用户有哪些可享用的折扣
    '''
    lists = []

    orders = Order.query.filter_by(user_id=session['user_id'], status='0').order_by(Order.ordered_time.desc()).all()
    if not orders:
        alipay_id = ''
    else:
        alipay_id = orders[0].alipay_id
    for order in orders:
        lists.append((ProductID.query.filter_by(id=order.detail.object.PID).first(), order.count, order.id))
    return render_template('usr/unpay.html', lists=lists, alipay_id=alipay_id)


@usr.route('/before_send', methods=['get'])
def before_send():
    '''

    order_dict={'alipay_id1':{'orders':[order1,order2,],'sum':sum},'alipay_id2':{...}}
    '''
    user_id = session.get('user_id')
    orders = Order.query.filter_by(user_id=user_id, status='2').order_by(Order.ordered_time.desc()).all()
    order_dict = {}
    for order in orders:
        if order.alipay_id not in order_dict:
            order_dict[order.alipay_id] = {}
            order_dict[order.alipay_id]['orders'] = [order, ]
            order_dict[order.alipay_id]['sum'] = order.alipay_order.sum
        else:
            order_dict[order.alipay_id]['orders'].append(order)
    return render_template('usr/has_payed.html', order_dict=order_dict)


@usr.route('/go_pay', methods=['post'])
def redirect_alipay():
    alipay_id = request.form.get('alipay_id')
    money = float(AlipayOrder.query.filter_by(id=int(alipay_id)).first().sum)
    # 生成一个对象
    alipay = ali()
    # 生成支付的url
    # 对象调用direct_pay
    # 该方法生成一个加密串
    query_params = alipay.direct_pay(
        subject="hy商城购物订单",  # 商品简单描述
        out_trade_no=str(alipay_id),  # 商户订单号
        total_amount=money,  # 交易金额(单位: 元 保留俩位小数)
    )
    pay_url = "https://openapi.alipaydev.com/gateway.do?{}".format(query_params)
    return jsonify({'status': 'success', 'url': pay_url})


def get_cart_count(user_id):
    user_cart_list = rd.hget('user_cart', user_id)
    if not user_cart_list:
        return 0
    user_cart_list=json.loads(user_cart_list)
    sum = 0
    for items in user_cart_list:
        sum += int(items[1])
    return sum

proj/web/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from flask import Blueprint

web = Blueprint(
    'web',
    __name__,
    template_folder='templates',
    static_folder='static'
)
from . import views

proj/templates/web/basehome.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>home</title>
    <link rel="stylesheet" href="/static/base/css/bootstrap.css">
    <style>
        .background {
            background-color: #ccc;
        }

        .search {
            background-color: white;
            margin: 10px 0;
        }

        .navbar-default {
            background-color: white;
            border: none;
        }
    </style>
    {% block css %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default ">
    <div class="container-fluid background">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Hy商城-电脑配件</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                {% if not session.user %}
                    <li><a href="/login">登陆</a></li>

                    <li><a href="/register/">注册</a></li>
                {% else %}
                    <li><a href="/user/">{{ session.user }}</a></li>
                {% endif %}
                <li><a href="#">PLUS会员</a></li>
                <li><a href="{{ url_for('usr.user_order') }}">我的订单</a></li>
                <li><a href="{{ url_for('usr.cart') }}">购物车<span class="badge">{{ session.cart_count }}</span></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">用户中心 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% if session.user %}
                            <li><a href="/logout/">用户注销</a></li>
                        {% endif %}
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    {% block search %}
    {% endblock %}
    {% if index %}
        <div class="container col-md-10 col-md-offset-1">
            <div class="row">
                <img src="/static/files/f132a09d6ac066be.jpg!q90.jpg/" alt="" style="margin-top: 10px">
            </div>
        </div>
    {% endif %}


</nav>
</body>
</html>
<script src="/static/base/js/jquery.min.js"></script>
<script src="/static/base/js/bootstrap.js"></script>
{% block script %}

{% endblock %}

proj/templates/web/email_auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>请在邮箱中确认激活信息激活后请访问 <a href="{{ url_for('web.login') }}">点我返回主页</a></p>
</body>
</html>

proj/templates/web/index.html
{% extends 'web/basehome.html' %}
{% block search %}
    <div class="row search">
        <div class="container">
            <div class="col-lg-6 col-lg-offset-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for..." id="search">
                    <span class="input-group-btn">
        <button class="btn btn-default " type="button"><a class="query" href="{{ url_for('web.query') }}?query=">搜索</a></button>
      </span>
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </div>
    </div>
    <div class="container">
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="true">
                电脑配件
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="{{ url_for('web.get_list') }}?cat=cpu">CPU</a></li>
                <li><a href="#">显卡</a></li>
            </ul>
        </div>
    </div>
    {% block result %}
    {% endblock %}

{% endblock %}
{% block script %}
    <script>
    $('#search').on('input propertychange',function () {
        var condition=$(this).val();
        $('.query').attr('href','query_cpu?query='+condition)
    })
    </script>
{% endblock %}

proj/templates/web/list_result.html
{% extends 'web/index.html' %}
{% block css %}
    <style>
        .thumbnail p {
            margin: 0;
            padding: 0;
        }
    </style>
{% endblock %}

{% block result %}
    <div class="container">
        <div class="panel panel-default col-md-offset-2">
            <div class="panel-heading">查询结果</div>
            <div class="panel-body">
                <div class="row">
                    {% if list %}
                        {% for item in list.items %}
                            <div class="col-sm-6 col-md-3">
                                <div class="thumbnail">
                                    <a href="{{ url_for('web.product_detail') }}?item={{ item.id }}"
                                       title="{{ item.object.slogan }}"><img
                                            src="/static{{ item.object.commodity_figure_path }}" alt=""></a>
                                    <div class="caption">
                                        <p><strong
                                                style="color: red;font-size: 15px">￥{{ item.object.sale_price }}</strong>
                                        </p>
                                        <a style="font-size: 11px;cursor: pointer;text-decoration: none"
                                           title="{{ item.object.slogan }}">{{ item.object.name|truncate(25) }}</a>
                                        <p><span
                                                style="font-size: 11px;color: #ffaa71 ">{{ item.object.slogan|truncate(20) }}</span>
                                        </p>
                                        <p><a href="">{{ item.object.store.name }}</a></p>

                                    </div>
                                </div>
                            </div>

                        {% endfor %}

                    {% else %}
                        <h3>暂无商品</h3>
                    {% endif %}


                </div>
                <div class="row">
                    {% if list.has_prev %}
                        <a href="{{ url_for('web.get_list', page=list.prev_num) }}">&lt;&lt;
                            上一页</a>{% else %}
                        &lt;
                        &lt; 上一页{% endif %} |
                    {% if list.has_next %}
                        <a href="{{ url_for('web.get_list', page=list.next_num) }}">下一页
                            &gt;&gt;</a>{% else %}
                        下一页 &gt;&gt;{% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

proj/templates/web/product_detail.html
{% extends 'web/basehome.html' %}
{% block css %}
    <style>
        .spinner {
            width: 100px;
        }

        .spinner input {
            text-align: right;
        }

        .input-group-btn-vertical {
            position: relative;
            white-space: nowrap;
            width: 1%;
            vertical-align: middle;
            display: table-cell;
        }

        .input-group-btn-vertical > .btn {
            display: block;
            float: none;
            width: 100%;
            max-width: 100%;
            padding: 8px;
            margin-left: -1px;
            position: relative;
            border-radius: 0;
        }

        .input-group-btn-vertical > .btn:first-child {
            border-top-right-radius: 4px;
        }

        .input-group-btn-vertical > .btn:last-child {
            margin-top: -2px;
            border-bottom-right-radius: 4px;
        }

        .input-group-btn-vertical i {
            position: absolute;
            top: 0;
            left: 4px;
        }

        .ll span {
            margin-right: 50px;
            display: inline-block;
        }
    </style>
{% endblock %}
{% block search %}
    <div class="row search">
        <div class="container">
            <div class="col-lg-6 col-lg-offset-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
        <button class="btn btn-default" type="button">搜索</button>
      </span>
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </div>
    </div>
    <div class="container-fluid">
        <img src="/static/{{ obj.object.store.nav_bar_image }}" class="img-responsive" alt="Responsive image">
    </div>
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{{ url_for('web.index') }}">首页</a></li>
            <li><a href="#">电脑配件</a></li>
            <li><a href="">{{ obj.category }}</a></li>
            <li class="active"><a href="">{{ obj.object.detail.brand }} {{ obj.object.detail.model }}</a></li>
        </ol>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <a href="" class="thumbnail">
                    <img src="/static{{ obj.object.commodity_figure_path }}" alt="..."
                         style="width: 400px;height: 400px">
                </a>
            </div>
            <div class="col-md-7">
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading"><strong>{{ obj.object.name }}</strong></h4>
                        <h6 style="color: #e4393c">{{ obj.object.slogan }}</h6>
                        <div class="well well-sm">h y 价：<span
                                style="color: red">￥<b>{{ obj.object.sale_price }}</b></span></div>
                    </div>
                    <div class="jumbotron">
                        <h1>其他附加选项留白</h1>
                    </div>
                    <hr>
                    <div class="container">
                        <div class="col-md-2">
                            <div class="input-group spinner">
                                <input type="text" class="form-control" id="count" value="1">
                                <div class="input-group-btn-vertical">
                                    <button class="btn btn-default" type="button"><i class="fa fa-caret-up">+</i>
                                    </button>
                                    <button class="btn btn-default" type="button"><i class="fa fa-caret-down">-</i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <p><a class="btn btn-primary btn-lg" id="add" role="button"
                                  style="color:whitesmoke;">添加到购物车</a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <ul class="nav nav-pills">
                            <li role="presentation" class="active"><a href="#">商品介绍</a></li>
                            <li role="presentation"><a href="#">规格与包装</a></li>
                            <li role="presentation"><a href="#">商品评价</a></li>
                        </ul>
                    </div>
                    <div class="panel-body ll">
                        <p>品牌: <a href="">{{ obj.object.detail.brand }}</a></p>
                        <span>商品名称：{{ obj.object.detail.brand }} {{ obj.object.detail.model }}</span>
                        <span>商品编号：{{ obj.id }}</span>
                        <span>接口：{{ obj.object.detail.interface }}</span>
                        <span>搭配主板：{{ obj.object.detail.match_mainboard }}</span>
                        <span>处理器({{ obj.object.detail.brand }}):{{ obj.object.detail.series }}</span>
                    </div>
                </div>
            </div>
        </div>
    <div class="container col-md-offset-3">
        {% for image in obj.detail_image %}
        <img src="/static{{ image.path }}" alt="" style="margin-top: 10px">

        {% endfor %}


    </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        (function ($) {
            $('.spinner .btn:first-of-type').on('click', function () {
                $('.spinner input').val(parseInt($('.spinner input').val(), 10) + 1);
            });
            $('.spinner .btn:last-of-type').on('click', function () {
                if ($('.spinner input').val() > 1) {
                    $('.spinner input').val(parseInt($('.spinner input').val(), 10) - 1);
                }

            });
        })(jQuery);


        $('#add').on('click', function () {
            $.ajax({
                url:'{{ url_for('usr.add_to_cart') }}',
                method: 'post',
                data: {'count': $('#count').val(), 'pid':{{ obj.id }}},
                success: function (data) {
                    if (data.status == 'success') {
                        window.location.href = data.url
                    }
                }

            })
        })
    </script>
{% endblock %}